// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SingularityLimitedPhaseOneTest.Data;

namespace SingularityLimitedPhaseOneTest.Migrations
{
    [DbContext(typeof(SingularityLimitedPhaseOneTestContext))]
    [Migration("20210220192819_seed product values")]
    partial class seedproductvalues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("SingularityLimitedPhaseOneTest.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("SKU")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Product 101 des",
                            Name = "Product 101",
                            Price = 10.0,
                            SKU = "#001"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Product 102 des",
                            Name = "Product 103",
                            Price = 20.0,
                            SKU = "#002"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Product 103 des",
                            Name = "Product 102",
                            Price = 30.0,
                            SKU = "#003"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
